
import styles from "./page.module.css";

export default function AdminPanel() {
  return (
    <div className={styles.admin_panel}>
        AQUI VA EL PANEL DE ADMINISTRACION DONDE SE MUESTRA INFORMACION
        GENERAL DE INTERES COMO (NUMERO DE ORDENES EN EL SISTEMA, CUANTAS
        ACTIVAS, CUANTAS ENTREGADAS, CUANTAS CANCELADAS, CUANTAS PENDIENTES)
        NUMERO DE CLIENTES REGISTRADOS, NUMERO DE PRODUCTOS EN EL SISTEMA
        Y UNA ALERTA SI HAY PRODUCTOS BAJOS DE INVENTARIO
    </div>
  );
}
