
import styles from "../../page.module.css";

export default function Reports() {
  return (
    <div className={styles.reports_container}>
      AQUI VA DISTINTAS OPCIONES DE REPORTES (VENTAS, ORDENES ACTIVAS, ORDENES COMPLETADAS
        ORDENES CANCELADAS, PRODUCTOS MAS VENDIDOS, PRODUCTOS MENOS VENDIDOS, CLIENT
        ES MAS FRECUENTES, CLIENTES QUE MAS COMPRAN, CLIENTES QUE MAS CANCELAN ORDENES)
        DEBEN EXISTIR GRAFICAS QUE MUESTREN LOS REPORTES Y LA POSIBILIDAD DE DESCARGARLOS
        EN FORMATO CSV
    </div>
  );
}
